fix(zod): allow custom markDefs to passthrough zod
saiichihashimoto/sanity-typed pull request #456
Opened 2023-11-02 21:50 UTC by mckelveygreg

I just started using @sanity-typed/zod to parse responses, but I noticed it was stripping out custom markDefs from my `block` content. 

Adding `passthrough` keeps those fields from getting removed, and I'm not sure how else you would want to integrate this, as the block types seem to get very complicated!

I added some tests (though I had a hard time running them very well locally...)

2023-11-03 17:34 UTC, saiichihashimoto commented
I haven't taken a look at this yet, will be getting to this soon!

2023-11-06 21:29 UTC, saiichihashimoto requested changes
Maybe `git commit --amend` to rerun linting, or just `npm run lint` and make another commit. I've added an eslint plugin that addresses some of the spacing comments I was going to make.

Also, looks like some of the existing tests might be failing.

2023-11-06 21:29 UTC, saiichihashimoto commented on packages/zod/src/block.test.ts
> +    it("builds parser for custom markDefs", () => {
I'd change this to "allows custom markDefs". It's definitely not parsing them.

2023-11-06 21:29 UTC, saiichihashimoto commented on packages/zod/src/block.test.ts
> +    it("builds parser for custom markDefs", () => {
Same.

2023-11-06 21:38 UTC, mckelveygreg commented
Linting updated.

Yeah, making that a `.passthough()` seems to break the `InferSchemaValues`

2023-11-07 21:08 UTC, saiichihashimoto commented
Yeah it looks like you'll need to see what `passthrough()` actually does to the types and add them to the corresponding `@sanity-typed/types` type for it to make sense.

2023-11-10 18:22 UTC, saiichihashimoto commented
Once you're able to figure out what's the fix for `types` or for the zod parser to have them match, we should be good to go.

2023-11-10 18:27 UTC, mckelveygreg commented
I haven't had a chance to troubleshoot. I have the dist patched so it will work in our project, but will have to come back to the types so we can have a proper fix 😞

2023-12-10 22:20 UTC, saiichihashimoto commented
@mckelveygreg if I can fix the bugs in #535, we might actually have a more strongly typed solution than `passthrough()`, which actually enforces the types match what are in `marks.annotations`.

2023-12-11 04:15 UTC, saiichihashimoto commented
@mckelveygreg Can you try `@sanity-typed/types@6.0.0` and `@sanity-typed/zod@2.0.0`? `markDefs` are now checked against the `marks.annotations` provided to the `block` definition, so the zod parser and types should correlate to your config instead of using `passthrough()`.

2023-12-11 17:58 UTC, mckelveygreg commented
Hmm, i spent some time trying to get things updated, but I was getting infinite instantiation errors if I had anything in the `annotations` field (even with `definedArrayMember` and `defineField` just like in your new docs). 
I'll have to comeback later for updates 🤷 

Thanks for keeping me in the loop!
But it looks like this PR can probably close because you have taken a different direction?

2023-12-11 18:19 UTC, saiichihashimoto commented
Would you be able to create an issue with your config that is creating the infinite instantiation issue so I can debug it?

2023-12-11 18:19 UTC, saiichihashimoto commented
But yes, I'll close this!

2023-12-11 18:19 UTC, closed without merging